image: node:7.8

variables:
  NODE_ENV: production

cache:
  key: $CI_COMMIT_REF_NAME
  untracked: true
  paths:
    - node_modules/
    - npm_cache/

build:
  stage: build
  script:
    - ln -s /usr/local/bin/node /usr/bin/node
    - npm config set cache npm_cache/
    - npm install gulp -g --loglevel warn
    - npm install --unsafe-perm --loglevel warn # unsafe-perm because some scripts may not run with root privileges
    - gulp build
  artifacts:
    paths:
      - dist/
