image: cusspvz/node:7.8.0-development

variables:
  NODE_ENV: production

cache:
  key: $CI_COMMIT_REF_NAME
  untracked: true
  paths:
    - node_modules/
    - npm_cache/

before_script:
  - npm config set cache npm_cache/

build:
  stage: build
  script:
    - npm install gulp -g --loglevel warn
    - npm install --loglevel warn
    - gulp build
  artifacts:
    name: "website-${CI_COMMIT_REF_NAME}"
    paths:
      - dist/
