variables:
  DOCKER_DRIVER: overlay
  STAGING_BUCKET_NAME: site.stg-example-com
  STAGING_URL: http://stg.example.com
  PRODUCTION_BUCKET_NAME: site.example-com
  PRODUCTION_URL: https://example.com
  PRODUCTION_CLOUDFRONT_DISTRIBUTION_ID: XXXXXXXX

stages:
  - build
  - package

build:
  stage: build
  image: cusspvz/node:7.8.0-development
  script:
    - npm install gulp -g --loglevel warn
    - npm install --loglevel warn
    - gulp clean
    - gulp build-deps
    - gulp build
    - gulp test-pages
  cache:
    key: $CI_COMMIT_REF_NAME
    untracked: true
    paths:
      - node_modules/

deploy_to_production:
  stage: deploy
  image: python:latest
  environment:
    name: production
    url: $PRODUCTION_URL
  script:
    - pip install awscli
    - aws configure set preview.cloudfront true
    - aws s3 sync dist/ s3://$STAGING_BUCKET_NAME/ --delete
    - aws cloudfront create-invalidation --distribution-id $PRODUCTION_CLOUDFRONT_DISTRIBUTION_ID --paths '/*'
  when: manual
  only:
    - master

deploy_to_staging:
  stage: deploy
  image: python:latest
  environment:
    name: staging
    url: $STAGING_URL
  script:
    - pip install awscli
    - aws s3 sync dist/ s3://$PRODUCTION_BUCKET_NAME/ --delete
  only:
    - develop
