image: node:7.8

cache:
  key: $CI_BUILD_REF_NAME
  untracked: true
  paths:
    - node_modules/

build:
  stage: build
  script:
    - ln -s /usr/bin/nodejs /usr/bin/node
    - npm install gulp -g
    - npm install
    - gulp build
  artifacts:
    paths:
      - dist/
